name: Flutter CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.6'
          cache: false

      - name: Install dependencies
        run: flutter pub get
        working-directory: octavus

      - name: Run tests with coverage
        run: flutter test --coverage
        working-directory: octavus

      - name: Check coverage threshold
        run: |
          COVERAGE=$(grep -E 'lines\.*:' octavus/coverage/lcov.info | awk '{print $3}')
          echo "Cobertura de linhas: $COVERAGE"
          COVERAGE_INT=${COVERAGE%.*}
          if [ "$COVERAGE_INT" -lt 70 ]; then
            echo "Cobertura menor que 70%, falhando o job."
            exit 1
          fi

      - name: Upload coverage report
        uses: actions/upload-artifact@v4
        with:
          name: coverage-report
          path: octavus/coverage/lcov.info
