name: Flutter CI

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.6'
          cache: false

      - name: Install dependencies
        run: flutter pub get
        working-directory: octavus

      - name: Run tests with coverage
        run: flutter test --coverage
        working-directory: octavus

      - name: Validate coverage (>= 70%)
        run: |
          COVERAGE=$(grep -E '^\s*LF:' octavus/coverage/lcov.info | awk -F':' '{sum += $2} END {print sum}')
          HITS=$(grep -E '^\s*LH:' octavus/coverage/lcov.info | awk -F':' '{sum += $2} END {print sum}')
          PERCENT=$(awk -v h=$HITS -v t=$COVERAGE 'BEGIN { if (t > 0) printf "%.2f", (h/t)*100; else print 0 }')

          echo "Total lines: $COVERAGE"
          echo "Lines hit: $HITS"
          echo "Cobertura: $PERCENT%"

          PERCENT_INT=${PERCENT%.*}
          if [ "$PERCENT_INT" -lt 70 ]; then
            echo "❌ Cobertura abaixo de 70%"
            exit 1
          else
            echo "✅ Cobertura OK (>= 70%)"
          fi

      - name: Upload lcov.info
        uses: actions/upload-artifact@v4
        with:
          name: lcov.info
          path: octavus/coverage/lcov.info

      - name: Optional HTML report (genhtml)
        run: |
          sudo apt-get update && sudo apt-get install -y lcov
          genhtml coverage/lcov.info --output-directory=coverage/html --ignore-errors source || echo "⚠️ genhtml falhou"
        working-directory: octavus

      - name: Upload HTML report
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: html-coverage-report
          path: octavus/coverage/html
